name: Build and Push Docker image on PR to main

on:
  pull_request:
    branches:
      - main
    paths:
      - "application/**"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: AnkitPatel/cst8918-a01-weather-app
          tags: |
            type=sha,prefix=sha-,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./application
          file: ./application/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest output
        run: echo "The image digest is ${{ steps.meta.outputs.digest }}"
